### ISSUE TITLE
为什么写博客？

### ISSUE THREAD

**Issue by chiehw** [chiehw/weekly#1]
我能感受到，我博客的文字非常生硬。读阮一峰的博客时，总能感受到丝滑和~~情切~~亲切。我也能感受到，我博文的顺序是混乱的。

现在的我，想把博文写好，但遇到了几个问题：

1. 写什么？
2. 什么叫写好？
3. 怎么写才能写好？
---

未来几周，可能会找点写作相关的书籍，帮助我自己改善写作技能。
> 每周花一个小时来学习写作吧。

**Comment by asur4s** [comment]
第一本书：《写作这回事》
