### ISSUE TITLE
在 22 岁的时候写给 25 岁的自己

### ISSUE THREAD

**Issue by chiehw** [chiehw/weekly#3]
前段时间面试字节的飞书，上周二上午四面。已经等了一周了，迟迟没有收到四面的消息。有些急躁，前段时间养成的习惯都逐渐被这些急躁的心情弄得支离破碎。

今天在网上闲逛时，发现了几篇写得不错的文章——[《愿路途不再往复》](https://soyn.github.io/2016-10-02-%E6%84%BF%E8%B7%AF%E9%80%94%E4%B8%8D%E5%86%8D%E5%BE%80%E5%A4%8D%EF%BC%8C%E6%84%BF%E6%97%A0%E5%B2%81%E6%9C%88%E5%8F%AF%E5%9B%9E%E5%A4%B4/)、[《在21岁的时候写给25岁的自己》](https://soyn.github.io/2016-11-26-%E5%86%99%E7%BB%9925%E5%B2%81%E7%9A%84%E8%87%AA%E5%B7%B1/)、[《我的2013：我来到了美国》](http://wangcong.org/2014/01/30/-e6-88-91-e7-9a-842013-ef-bc-9a-e6-88-91-e6-9d-a5-e5-88-b0-e4-ba-86-e7-be-8e-e5-9b-bd/)。我昨天刚刚过完 22 岁的生日，我的标题应该是《在 22 岁的时候写给 25 岁的自己》。

---

首先感谢你能在繁忙的工作或学习中打开这篇文章，这个时候也许是某个深夜，也许是在某个清晨，或者是某个失意的时刻。当你看到当年写下的文字，心里无论是感到可笑，还是幼稚，请好好生活，不要辜负 22 岁的你对你的期望。

人生是没有意义的，任何人都是光着身子来，都是光着身子走，但没意义的人生并不代表无需继续。如果你已经忘记了这段话有多么的深刻，请重读一下《西西弗神话》吧。

既然人生没有意义，那么不如让它变得更精彩更耀眼吧。这并不是要求你没日没夜的去为了某个目标而熬夜，而是找出自己内心中想要的东西，选择能产生复利效应的东西，并勇敢的去追求他。有欲望并不是坏事，关键在于欲望将我们引向何方。

在追寻某个东西的过程，比结果更为重要。在追寻过程中，没必要将自己的所有精力都放在目标上，别忘了你还有身体、家人、朋友需要呵护。

## 身体

在新闻和网络上看到了不少程序员加班猝死的新闻，我不希望未来名单里多了你的名字。

身体是革命的本钱，希望你这时候已经有了健身的习惯。不要坐的太久，定时起来运动一下。每个周六周日都会和朋友打打球或者跑跑步。

这时候的你，周末应该自己做饭，还可以邀请一下同事或者朋友来家里聚餐。做饭其实和写代码一样，稍微在网上学一下就可以做得很好吃。

## 工作和学习

尽力做好每个小任务并时刻保持学习，这才是真正的生活。不要试图平衡工作、生活、学习，这是一个不现实的理想。也不要逃避困难，你今天逃过的困难可能就是明天的绊脚石。

这时候的你已经有了一些工作经验，请做好交给你的任何任务。抱怨是最没用的行为，浪费时间且影响心情。

## 生活

这时候希望你能有一段稳定的感情，有能够理解和支持你的女朋友，但是如果没有，也不要失望，就算是一个人，也要过的很有趣。

这时候希望你能有一定的积蓄，至少能够保证你即使一年不工作，原有的生活质量不会受影响，如果可以的话，最好能投资一点理财产品。

最后，想给 25 岁的你说，即使以上说的所有事你都没有办到，请你也不要失望和灰心。

**Comment by L0nm4r** [comment]
加油 :)
